services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kyager_app
    container_name: kyager_app
    restart: unless-stopped
    environment:
      - DB_HOST=kyager_db
      - DB_DATABASE=challenge_kyager
      - DB_USERNAME=root
      - DB_PASSWORD=root_password
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"  # Asegúrate de que el puerto no esté en uso
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: kyager_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: challenge_kyager
      MYSQL_PASSWORD: root_password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: